# Generated by Django 6.0.3 on 2026-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('vendedor', models.CharField(default='anônimo', max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em ')),
            ],
        ),
    ]
